# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Derek is a Dev
email: hello@derekbaker.dev
description: >- # this means to ignore newlines until "baseurl:"
  These are my notes and thoughts as I travel through a career in software development.
twitter_username: derekisadev
github_username: backslashbaker
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: UCT

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Derek Baker"
  avatar : "/assets/images/new-profile-image.jpeg"
  bio    : "I try to build things with code."
  location : "London, UK"
  links:
    - label: "Email"
      icon:  "fas fa-fw fa-envelope-square"
      url: "mailto:hello@derekbaker.dev"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://derekbaker.dev"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/derekisadev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/backslashbaker"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/derekisadev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/backslashbaker"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hello@derekbaker.dev"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
