# Setup
title:              Derek Baker 
tagline:             'A lost developer'
description:         'Thoughts and learnings on my software developing journey'
url:                 https://derekbaker.dev
baseurl:             '' 
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Derek Baker
  url:               https://twitter.com/backslashbaker
  email:             hello@derekbaker.dev

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
